@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nReadOnlyTaskList" as ReadOnlyTaskList
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs
Class TaskList
Class Task

Class UniquePersonList
Class Person
Class Username
Class Email
Class Name
Class Phone
Class Tag
Class Link

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up..|> ReadOnlyAddressBook
TaskList .up..|> ReadOnlyTaskList

ModelManager .up.|> Model
Model .down.> ReadOnlyUserPrefs
Model .down.> ReadOnlyAddressBook
Model .down.> ReadOnlyTaskList
ModelManager -left-> "1" AddressBook
ModelManager -up-> "1" UserPrefs
ModelManager -right-> "1" TaskList
UserPrefs .up.|> ReadOnlyUserPrefs

TaskList --> "~* " Task

AddressBook *--> "1" UniquePersonList
UniquePersonList --> "~* " Person
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Username
Person *--> "*" Tag

Task -> "*" Tag
Task -down-> "0 .. 1" Link

Name -[hidden]right-> Phone
Task -[hidden]left-----> Person


ModelManager -->"~*" Person
ModelManager -->"~*" Task
@enduml
